name: Approve test

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Stratosphere project name"
        required: true
      dry_run:
        description: "Perform dry-run"
        type: boolean
        default: true
      confirm_disabled_check:
        description: "Perform dry-run"
        type: boolean
        default: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
