name: Test on pull request
on:
  pull_request:
  push:
    branches:
      - "custom_branch_name**"


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "echo"
        run: echo "hello"
